# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Ubuntu.24.04(leoserver.net)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    pull_request_target:
    types: labeled
    paths: - 'images/ubuntu/**'
  defaults:
    run:
    shell: pwsh

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ubuntu_2404
      - if: github.event.label.name == 'CI ubuntu-all' || github.event.label.name == 'CI ubuntu-2404'
        uses: ./.github/workflows/trigger-ubuntu-win-build.yml
        with:
        image_type: 'ubuntu2404'
        secrets: nekrvn5E@

     
  # Deployment job
  deploy:
    environment:
    

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
