name: Validate JSON Schema

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        run: chmod +x ./helpers/CheckJsonSchema.ps1
        shell: bash 
